In [1]:
%pylab inline
import pandas as pd
from Memory import Storage

Populating the interactive namespace from numpy and matplotlib


https://adventofcode.com/2021/day/3#part2

In [2]:
with open('data/day3.txt') as fid:
    lines=fid.readlines()

In [3]:
lines[:10]

['100100110110\n',
 '101110110110\n',
 '010100010100\n',
 '011001110000\n',
 '000000000111\n',
 '000010110001\n',
 '001111000001\n',
 '100010000001\n',
 '010100110011\n',
 '010000010110\n']

In [5]:
bins=[]
for line in lines:
    bits=[int(_) for _ in line.strip()]
    bins.append(bits)
    
bins=array(bins)
bins

array([[1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 1]])

In [8]:
gamma_binary=median(bins,axis=0)
gamma_binary

array([1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.])

In [10]:
p=arange(len(gamma_binary)-1,-1,-1)
p

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
gamma=(gamma_binary*2**p).sum()
gamma

3527.0

In [13]:
epsilon=((1-gamma_binary)*2**p).sum()
epsilon

568.0

In [14]:
gamma*epsilon

2003336.0

In [15]:
median([0,1])

0.5

In [16]:
bins

array([[1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 1]])

In [17]:
c=0

In [22]:
m=median(bins[:,0])
if m>0:
    m=1
else:
    m=0

In [23]:
bins2=bins[bins[:,0]==m]

In [24]:
bins2

array([[1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       ...,
       [1, 1, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1]])

In [33]:
lines="""
00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
""".strip().split('\n')

In [61]:
with open('data/day3.txt') as fid:
    lines=fid.readlines()

In [62]:
bins=[]
for line in lines:
    bits=[int(_) for _ in line.strip()]
    bins.append(bits)
    
bins=array(bins)
bins

array([[1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 1]])

In [63]:
c=0
print(bins.shape[0])
while bins.shape[0]>1:
    m=median(bins[:,c])
    if m>0:
        m=1
    else:
        m=0   
        
    bins=bins[bins[:,c]==m]
    print(bins.shape[0])
    c+=1
    
bins

1000
509
256
133
70
38
23
12
8
5
3
2
1


array([[1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1]])

In [64]:
O2=(bins*2**p).sum()
O2

2547

In [65]:
lines="""
00100
11110
10110
10111
10101
01111
00111
11100
10000
11001
00010
01010
""".strip().split('\n')

In [66]:
with open('data/day3.txt') as fid:
    lines=fid.readlines()

In [67]:
bins=[]
for line in lines:
    bits=[int(_) for _ in line.strip()]
    bins.append(bits)
    
bins=array(bins)
bins

array([[1, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 1, 1, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 1, 1]])

In [68]:
c=0
print(bins.shape[0])
while bins.shape[0]>1:
    m=median(bins[:,c])
    m=1-m # least popular
    if m<1:
        m=0
    else:
        m=1   
        
    
    #print(c,m,median(bins[:,c]),bins[:,c])
    bins=bins[bins[:,c]==m]
    #print(bins)
    print(bins.shape[0])
    c+=1
    
bins

1000
491
222
105
50
23
9
4
2
1


array([[0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1]])

In [69]:
CO2=(bins*2**p).sum()
CO2

737

In [70]:
O2*CO2

1877139