In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [56]:
text="""5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
""".strip()

def text2arr(text):
    lines=text.strip().split('\n')
    arr_str=[[int(_) for _ in line] for line in lines]
    arr=array(arr_str)
    return arr

arr=text2arr(text)
arr

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [19]:
from numba import njit

In [44]:
# @njit
def step(arr):
    arr=arr.copy()
    r,c=arr.shape
    
    for i in range(r):
        for j in range(c):
            arr[i,j]+=1
            
    flash=True
    while flash:
        flash=False
        for i in range(r):
            for j in range(c):
                if arr[i,j]>9:
                    arr[i,j]=0  # flash!
                    flash=True

                    for i2 in [i-1,i,i+1]:
                        for j2 in [j-1,j,j+1]:
                            if i2<0 or j2<0 or i2>=r or j2>=c or (i2==i and j2==j):
                                continue
                            if arr[i2,j2]>0:
                                arr[i2,j2]+=1

    return arr


In [45]:
arr

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [46]:
arr1=step(arr)
arr1

array([[6, 5, 9, 4, 2, 5, 4, 3, 3, 4],
       [3, 8, 5, 6, 9, 6, 5, 8, 2, 2],
       [6, 3, 7, 5, 6, 6, 7, 2, 8, 4],
       [7, 2, 5, 2, 4, 4, 7, 2, 5, 7],
       [7, 4, 6, 8, 4, 9, 6, 5, 8, 9],
       [5, 2, 7, 8, 6, 3, 5, 7, 5, 6],
       [3, 2, 8, 7, 9, 5, 2, 8, 3, 2],
       [7, 9, 9, 3, 9, 9, 2, 2, 4, 5],
       [5, 9, 5, 7, 9, 5, 9, 6, 6, 5],
       [6, 3, 9, 4, 8, 6, 2, 6, 3, 7]])

In [47]:
arr2=step(arr1)
arr2

array([[8, 8, 0, 7, 4, 7, 6, 5, 5, 5],
       [5, 0, 8, 9, 0, 8, 7, 0, 5, 4],
       [8, 5, 9, 7, 8, 8, 9, 6, 0, 8],
       [8, 4, 8, 5, 7, 6, 9, 6, 0, 0],
       [8, 7, 0, 0, 9, 0, 8, 8, 0, 0],
       [6, 6, 0, 0, 0, 8, 8, 9, 8, 9],
       [6, 8, 0, 0, 0, 0, 5, 9, 4, 3],
       [0, 0, 0, 0, 0, 0, 7, 4, 5, 6],
       [9, 0, 0, 0, 0, 0, 0, 8, 7, 6],
       [8, 7, 0, 0, 0, 0, 6, 8, 4, 8]])

In [50]:
check_text="""
Before any steps:
5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526

After step 1:
6594254334
3856965822
6375667284
7252447257
7468496589
5278635756
3287952832
7993992245
5957959665
6394862637

After step 2:
8807476555
5089087054
8597889608
8485769600
8700908800
6600088989
6800005943
0000007456
9000000876
8700006848

After step 3:
0050900866
8500800575
9900000039
9700000041
9935080063
7712300000
7911250009
2211130000
0421125000
0021119000

After step 4:
2263031977
0923031697
0032221150
0041111163
0076191174
0053411122
0042361120
5532241122
1532247211
1132230211

After step 5:
4484144000
2044144000
2253333493
1152333274
1187303285
1164633233
1153472231
6643352233
2643358322
2243341322

After step 6:
5595255111
3155255222
3364444605
2263444496
2298414396
2275744344
2264583342
7754463344
3754469433
3354452433

After step 7:
6707366222
4377366333
4475555827
3496655709
3500625609
3509955566
3486694453
8865585555
4865580644
4465574644

After step 8:
7818477333
5488477444
5697666949
4608766830
4734946730
4740097688
6900007564
0000009666
8000004755
6800007755

After step 9:
9060000644
7800000976
6900000080
5840000082
5858000093
6962400000
8021250009
2221130009
9111128097
7911119976

After step 10:
0481112976
0031112009
0041112504
0081111406
0099111306
0093511233
0442361130
5532252350
0532250600
0032240000
"""

In [52]:
arrs=[]
for text2 in check_text.split("\n\n"):
    arrs.append(text2arr(text2.split(":")[1]))

In [53]:
arrs

[array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
        [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
        [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
        [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
        [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
        [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
        [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
        [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
        [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
        [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]]),
 array([[6, 5, 9, 4, 2, 5, 4, 3, 3, 4],
        [3, 8, 5, 6, 9, 6, 5, 8, 2, 2],
        [6, 3, 7, 5, 6, 6, 7, 2, 8, 4],
        [7, 2, 5, 2, 4, 4, 7, 2, 5, 7],
        [7, 4, 6, 8, 4, 9, 6, 5, 8, 9],
        [5, 2, 7, 8, 6, 3, 5, 7, 5, 6],
        [3, 2, 8, 7, 9, 5, 2, 8, 3, 2],
        [7, 9, 9, 3, 9, 9, 2, 2, 4, 5],
        [5, 9, 5, 7, 9, 5, 9, 6, 6, 5],
        [6, 3, 9, 4, 8, 6, 2, 6, 3, 7]]),
 array([[8, 8, 0, 7, 4, 7, 6, 5, 5, 5],
        [5, 0, 8, 9, 0, 8, 7, 0, 5, 4],
        [8, 5, 9, 7, 8, 8, 9, 6, 0, 8],
        [8, 4, 8, 5, 7, 6, 9, 6, 0, 0],
        [8, 7, 0, 0, 9, 0, 8, 8, 0, 

In [54]:
arr

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [66]:
arr1=arr
flash_count=0
for i in range(10):
    if all(arr1==arrs[i]):
        print(f"{i} ok")
    else:
        print(f"{i} bad")
        break
        
    arr1=step(arr1)
    flash_count+=(arr1==0).sum()
    
flash_count

0 ok
1 ok
2 ok
3 ok
4 ok
5 ok
6 ok
7 ok
8 ok
9 ok


204

In [67]:
arr1=arr
flash_count=0
for i in range(100):
    arr1=step(arr1)
    flash_count+=(arr1==0).sum()
    
flash_count

1656

In [68]:
with open('data/day11.txt') as fid:
    text=fid.read()
arr=text2arr(text)
arr

array([[6, 6, 1, 7, 1, 1, 3, 5, 8, 4],
       [6, 5, 4, 4, 2, 1, 8, 6, 3, 8],
       [5, 4, 5, 7, 3, 3, 1, 4, 8, 8],
       [1, 1, 3, 5, 6, 7, 5, 5, 8, 7],
       [1, 2, 2, 1, 3, 5, 3, 2, 1, 6],
       [1, 8, 1, 1, 1, 2, 4, 3, 7, 8],
       [1, 3, 8, 7, 8, 6, 4, 3, 6, 8],
       [4, 4, 2, 7, 6, 3, 7, 2, 6, 2],
       [6, 7, 7, 8, 6, 4, 5, 4, 8, 6],
       [3, 6, 8, 2, 1, 4, 6, 7, 4, 5]])

In [69]:
arr1=arr
flash_count=0
for i in range(100):
    arr1=step(arr1)
    flash_count+=(arr1==0).sum()
    
flash_count

1599

## part 2

In [73]:
text="""5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
""".strip()

In [74]:
arr=text2arr(text)
arr

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [75]:
arr1=arr
for i in range(200):
    arr1=step(arr1)
    if all(arr1==0):
        break
    
print(i)

194


In [77]:
arr1=arr
i=0
while not all(arr1==0):
    arr1=step(arr1)
    i+=1
    
print(i)

195


In [78]:
with open('data/day11.txt') as fid:
    text=fid.read()
arr=text2arr(text)
arr

array([[6, 6, 1, 7, 1, 1, 3, 5, 8, 4],
       [6, 5, 4, 4, 2, 1, 8, 6, 3, 8],
       [5, 4, 5, 7, 3, 3, 1, 4, 8, 8],
       [1, 1, 3, 5, 6, 7, 5, 5, 8, 7],
       [1, 2, 2, 1, 3, 5, 3, 2, 1, 6],
       [1, 8, 1, 1, 1, 2, 4, 3, 7, 8],
       [1, 3, 8, 7, 8, 6, 4, 3, 6, 8],
       [4, 4, 2, 7, 6, 3, 7, 2, 6, 2],
       [6, 7, 7, 8, 6, 4, 5, 4, 8, 6],
       [3, 6, 8, 2, 1, 4, 6, 7, 4, 5]])

In [79]:
arr1=arr
i=0
while not all(arr1==0):
    arr1=step(arr1)
    i+=1
    
print(i)

418
