In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
ex1="""
2199943210
3987894921
9856789892
8767896789
9899965678
""".strip()

In [3]:
text=ex1

In [4]:
lines=text.strip().split('\n')
arr_str=[[int(_) for _ in line] for line in lines]
arr=array(arr_str)
arr

array([[2, 1, 9, 9, 9, 4, 3, 2, 1, 0],
       [3, 9, 8, 7, 8, 9, 4, 9, 2, 1],
       [9, 8, 5, 6, 7, 8, 9, 8, 9, 2],
       [8, 7, 6, 7, 8, 9, 6, 7, 8, 9],
       [9, 8, 9, 9, 9, 6, 5, 6, 7, 8]])

In [5]:
from numba import jit

In [6]:
@jit(nopython=True)
def mins(arr):
    r,c=arr.shape
    
    vals=[]
    for i in range(r):
        for j in range(c):
            found=True
            val=arr[i,j]
            
            if i>0:
                if val>=arr[i-1,j]:
                    continue
            if i<r-1:
                if val>=arr[i+1,j]:
                    continue
            if j>0:
                if val>=arr[i,j-1]:
                    continue
            if j<c-1:
                if val>=arr[i,j+1]:
                    continue
                
            vals.append(val)
            
    return array(vals)
            

In [7]:
mins(arr)

array([1, 0, 5, 5])

In [8]:
sum(mins(arr)+1)

15

In [9]:
with open('data/day9.txt') as fid:
    text=fid.read()

In [10]:
lines=text.strip().split('\n')
arr_str=[[int(_) for _ in line] for line in lines]
arr=array(arr_str)
arr

array([[7, 6, 7, ..., 9, 6, 5],
       [6, 5, 6, ..., 8, 9, 3],
       [5, 4, 5, ..., 7, 8, 9],
       ...,
       [5, 6, 7, ..., 4, 5, 6],
       [6, 7, 8, ..., 6, 8, 7],
       [7, 9, 9, ..., 7, 9, 8]])

In [11]:
mins(arr)

array([0, 5, 1, 2, 0, 5, 0, 0, 0, 3, 0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 4, 0,
       0, 0, 1, 5, 0, 3, 3, 2, 0, 2, 2, 1, 0, 0, 0, 1, 5, 1, 0, 0, 0, 5,
       0, 2, 4, 1, 2, 4, 0, 0, 0, 4, 0, 1, 2, 2, 1, 1, 0, 2, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 1, 1, 0, 2, 3, 2, 2,
       0, 0, 1, 0, 2, 2, 0, 0, 2, 1, 1, 0, 0, 0, 3, 2, 3, 0, 1, 0, 1, 1,
       1, 6, 3, 3, 0, 4, 0, 0, 0, 1, 0, 1, 4, 1, 0, 0, 3, 0, 1, 0, 0, 0,
       2, 3, 5, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 4, 1,
       0, 2, 3, 4, 2, 0, 0, 2, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 0, 4, 2, 0,
       0, 1, 1, 0, 0, 1, 2, 3, 0, 0, 2, 1, 0, 3, 1, 1, 0, 3, 1, 1, 0, 1,
       3, 0, 1, 2, 0, 3, 0, 1, 2, 4, 3, 0, 2, 1, 0, 0, 1, 3, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0])

In [12]:
sum(mins(arr)+1)

480